<?php
/*
Template Name: Schedule Bids
*/
?>

<?php get_header(); ?>

<section style="padding-top: 100px;">
	
	<!-- Paste Template Below -->

<center><h1>4th of July Schedule Shells</h1></center>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Book3_filelist.xml">
<style id="Book2_6287_Styles">
<!--table
  {mso-displayed-decimal-separator:"\.";
  mso-displayed-thousand-separator:"\,";}
.xl156287
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:11.0pt;
  font-weight:400;
  font-style:normal;
  text-decoration:none;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:General;
  text-align:general;
  vertical-align:bottom;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
.xl676287
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:11.0pt;
  font-weight:400;
  font-style:normal;
  text-decoration:none;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:General;
  text-align:center;
  vertical-align:middle;
  border:.5pt solid windowtext;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
.xl686287
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:11.0pt;
  font-weight:400;
  font-style:normal;
  text-decoration:none;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:General;
  text-align:general;
  vertical-align:bottom;
  border:.5pt solid windowtext;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
.xl696287
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:11.0pt;
  font-weight:400;
  font-style:normal;
  text-decoration:none;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:"Medium Time";
  text-align:general;
  vertical-align:bottom;
  border:.5pt solid windowtext;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Book2_6287" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=294 style='border-collapse:
 collapse;table-layout:fixed;width:221pt'>
 <col width=82 style='mso-width-source:userset;mso-width-alt:2998;width:62pt'>
 <col width=107 style='mso-width-source:userset;mso-width-alt:3913;width:80pt'>
 <col width=105 style='mso-width-source:userset;mso-width-alt:3840;width:79pt'>
 <tr height=20 style='height:15.0pt'>
  <td colspan=3 height=20 class=xl676287 width=294 style='height:15.0pt;
  width:221pt'>Holiday Shells</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 style='height:15.0pt;border-top:none'>ID</td>
  <td class=xl686287 style='border-top:none;border-left:none'>Start</td>
  <td class=xl686287 style='border-top:none;border-left:none'>End</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>1</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>7:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>4:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>2</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>7:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>4:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>3</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>7:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>4:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>4</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>7:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>4:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>5</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>7:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>4:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>6</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>7:30
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>4:30
  AM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>7</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>7:30
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>4:30
  AM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>8</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>8:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>5:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>9</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>8:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>5:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>10</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>8:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>5:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>11</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>8:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>5:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>12</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>8:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>5:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>13</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>8:30
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>5:30
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>14</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>8:30
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>5:30
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>15</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>9:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>6:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>16</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>9:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>6:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>17</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>9:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>6:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>18</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>9:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>6:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>19</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>9:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>6:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>20</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>9:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>6:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>21</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>9:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>6:00
  PM</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl686287 align=right style='height:15.0pt;border-top:
  none'>22</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>9:00
  AM</td>
  <td class=xl696287 align=right style='border-top:none;border-left:none'>6:00
  PM</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=82 style='width:62pt'></td>
  <td width=107 style='width:80pt'></td>
  <td width=105 style='width:79pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>





	<!-- End Template -->

</section>


<?php get_footer(); ?>